# Generated by Django 2.1.1 on 2019-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='islemtarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih/Saat'),
        ),
    ]
