# Generated by Django 2.1.1 on 2019-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0003_auto_20190123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanicilar',
            name='decimalfield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
